export { default as HeroProfil } from './HeroProfil'
export { default as TentangKamiProfil } from './TentangKamiProfil'
export { default as Tema } from './Tema'
export { default as ProkerUnggulan } from './ProkerUnggulan'
export { default as DPL } from './DPL'
export { default as HumansAtBumiHiri } from './HumansAtBumiHiri'
